---
title: "Componentes"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(fpp3)
```


```{r}
empleo_tsbl <- us_employment |> 
  filter(year(Month)>=1990, Title=="Retail Trade") |> 
  select(-Series_ID)

#Download to csv
# Para crear una carpeta
#dir.create("datos")
#us_retail_employment |> 
#  write_csv("datos/empleo_eeuu.csv")
```

```{r}
autoplot(empleo_tsbl)
```


## Classical decomposition
```{r}
empleo_decomp <- empleo_tsbl |> 
  model(
    clasica=classical_decomposition(Employed,
                                    type="additive")
  )

empleo_decomp
```

### Components

```{r}
empleo_components <- empleo_decomp |> 
  components()
empleo_components

empleo_components |> 
  autoplot()
```

Con descomposicón simple la tendencia a veces suaviza más d elo que debería. Como la estacionalidad es un promedio por lo que se mantiene fija, lo cual puede causar problemas.

```{r}
empleo_tsbl |> 
  model(STL(Employed ~ trend(window=7) + season(window='periodic'),
    robust = TRUE)) |> 
  components() |> 
  autoplot()
```



