---
title: "Gastos"
author: "Luis Márquez"
format:
  html:
    embed-resources: true
    theme:
      light: minty
      dark: darkly
toc: true
df-print: paged
---

```{r}
#| warning: false
library(tidyverse)
library(fpp3)
library(plotly)
library(readxl)
library(tsibble)
library(tibble)
library(zoo)
library(lubridate)
```

```{r}
datos <- read_excel("Gasto.xlsx", sheet = 2)
```

```{r}
datos$Date <- as.Date(datos$Date)
```

```{r}
datos <- as_tsibble(datos, index = Date)
datos

d <- datos |> 
  autoplot(Expense)
ggplotly(d, dynamicTicks = TRUE)
```

# Estimación de modelos

```{r}
datos_fit <- datos |> 
  model(
    media = MEAN(Expense),
    naive = NAIVE(Expense),
    snaive = SNAIVE(Expense),
    drift = RW(Expense ~ drift())
  )
datos_fit
```
# Análisis de residuos

```{r}
datos_fit |> 
  augment()

datos_fit |> 
  augment() |> 
  features(.innov, ljung_box, lag = 10, dof = 0)
```

## Media

```{r}
#| warning: false
datos_fit |> 
  select(media) |> 
  gg_tsresiduals()
```

## Naive

```{r}
#| warning: false
datos_fit |> 
  select(naive) |> 
  gg_tsresiduals()
```

## Seasonal Naive

```{r}
#| warning: false
datos_fit |> 
  select(snaive) |> 
  gg_tsresiduals()
```

## Drift

```{r}
#| warning: false
datos_fit |> 
  select(drift) |> 
  gg_tsresiduals()
```

# Forecast

```{r}
#| warning: false

datos_fc <- datos_fit |> 
  forecast(h = "14 days")

datos_fc

datos_fc |> 
  autoplot(datos) + 
  facet_wrap(~.model) + 
  theme(legend.position = "bottom")

```

Los mejores son media y snaive

```{r}
datos_fc |> 
  filter(.model == "media") |> 
  autoplot()


m <- datos_fc |> 
  filter(.model == 'media')
m <- as_tibble(m)
m <- as_tsibble(m, index = Date)
km <- m |> 
  select(c(Date, .mean)) |> 
  autoplot(.mean) + ggtitle("Predicción media") + ylab("Gasto $") + xlab("Fecha")
ggplotly(km, dynamicTicks = TRUE)
```

```{r}
datos_fc |> 
  filter(.model == "snaive") |> 
  autoplot()


sn <- datos_fc |> 
  filter(.model == 'snaive')
sn <- as_tibble(sn)
sn <- as_tsibble(sn, index = Date)
ksn <- sn |> 
  select(c(Date, .mean)) |> 
  autoplot(.mean) + ggtitle("Predicción seasonal naive") + ylab("Gasto $") + xlab("Fecha")
ggplotly(ksn, dynamicTicks = TRUE)
```

