---
title: "Pron칩stico"
author: "Luis M치rquez"
format:
  html:
    embed-resources: true
    theme:
      light: minty
      dark: darkly
toc: true
df-print: paged
---

```{r}
#| warning: false
library(tidyverse)
library(fpp3)
library(plotly)
```

```{r}
#| warning: false
mex <- global_economy |> 
  filter(Country=='Mexico') |> 
  drop_na() |> 
  select(-c(Country, Code))

mex |> 
  features(Growth, features = guerrero)

m <- mex |> 
  autoplot(Growth)
ggplotly(m, dynamicTicks = TRUE)

mex |> 
  autoplot(box_cox(Growth, lambda = 0.7249))

```

# Estimaci칩n de los modelos

```{r}
mex_fit <- mex |> 
  model(
    media = MEAN(box_cox(Growth, lambda = 0.7249)),
    naive = NAIVE(box_cox(Growth, lambda = 0.7249)),
    drift = RW(box_cox(Growth, lambda = 0.7249) ~ drift())
  )
mex_fit
```

# Diagn칩stico de residuos

```{r}
# Si hay transformaciones se usa innovaciones ya que es con residuos
# transformados
mex_fit |> 
  augment()

mex_fit |> 
  augment() |> 
  features(.innov, ljung_box, lag = 10, dof = 0)
```

Como el p-value de los 3 modelos es mayor a nuestra $\alpha$: $p_{value} = 0.05$, **NO RECHAZAMOS** $H_0 : \text{"Los residuos son ruido blanco"}$.

## Media

```{r}
#| warning: false
mex_fit |> 
  select(media) |> 
  gg_tsresiduals()
```

## Naive

```{r}
#| warning: false
mex_fit |> 
  select(naive) |> 
  gg_tsresiduals()
```

## Drift

```{r}
#| warning: false
mex_fit |> 
  select(drift) |> 
  gg_tsresiduals()
```

# Forecast

```{r}
#| warning: false

mex_fc <- mex_fit |> 
  forecast(h = "6 years")

mex_fc

mex_fc |> 
  autoplot(mex)

mex_fc |> 
  autoplot(mex) + 
  facet_wrap(~.model)

mex_fc |> 
  autoplot(mex) + 
  facet_wrap(~.model) + 
  theme(legend.position = "bottom")
```

Residuo es (original - modelo)

```{r}
aus_livestock |> 
  distinct(Animal)
```

## Datos

```{r}
ovejas <- aus_livestock |> 
  filter(Animal == "Sheep",
         State == "New South Wales")
ovejas
ovejas |> 
  autoplot(Count)
```

## Train/Test

```{r}
ovejas_train <- ovejas |> 
  filter_index(.~"Dec. 2012")
ovejas_train
```

```{r}
ovejas_train |> 
  autoplot(Count)
```

