---
title: "SERIES PROYECTO final"
format: 
  html:
    df-print: paged
    embed-resources: true
editor: visual
---

### SERIES PROYECTO

##### Úrsula Vargas, Marianne Trujillo, Amanda Martínez

### Paqueterías

```{r}
#| message: false
library(tidyverse)
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(tsibbledata)
library(fpp3)
library(lubridate)
library(fable.prophet)
library(plotly)
```

### DATA

```{r}
train <- read_csv("train.csv", show_col_types = FALSE)
```

```{r}
data3 <- as_tsibble(train,index = date, key = c(store_nbr,family))
data3
```

### VISUALIZACIÓN

```{r}
#data3 %>% 
 # autoplot(sales) +
  #theme(legend.position = "none")
```

```{r}
dat3_train <- data3 %>% 
  filter_index(. ~ "2016-08-15")

#dat3_train %>% 
 # autoplot(sales)+
  #theme(legend.position = "none")
```

### NDIFFS Y NSDIFFS PARA EL MODELO ARIMA

```{r}
dat3_train |> 
  features(log(sales), unitroot_nsdiffs)
```

```{r}
dat3_train |> 
  features(log(sales), unitroot_ndiffs)
```

### MODELOS PROPUESTOS

```{r}
data3_fit <- dat3_train %>%
  group_by_key() %>%
  fill_gaps()%>%
  tidyr::fill(sales, .direction = "down" )%>%
    model(
    #media              = MEAN(sales),
    ingenuo            = NAIVE(sales),
    #ingenuo_estacional = SNAIVE(sales),
    #drift              = RW(sales ~ drift()),
    #snaivelog = SNAIVE(log(sales)),
    #arima   = ARIMA(log(sales) ~ 0 + pdq(0:2,1,0:2) + PDQ(0:2,1,0:2)),
    #Prophet        = prophet(sales ~ growth("linear") + season("year", type = "multiplicative")),

  )

data3_fit
```

### TABLA DE ERRORES

```{r}
data3_fit |> 
  accuracy() |> 
  arrange(MAPE)
```

### PRÓNOSTICO PARA 15 DÍAS DE CADA MODELO

```{r}
data3_fc <- data3_fit |> 
  forecast(h = "15 days")
data3_fc
```
