---
title: "Clase_2"
author: "Luis Márquez"
format:
  html:
    embed-resources: true
    theme:
      light: minty
      dark: darkly
toc: true
df-print: paged
---

```{r}
#| warning: false
library(tidyverse) # data science
library(fpp3) # ts
```

```{r}
aus_accommodation
```

```{r}
aus_accommodation_long <- aus_accommodation |> 
  pivot_longer(cols = Takings:CPI, names_to="variable",
               values_to = "valor")

aus_accommodation_long |> 
  features(valor,
           list(media = mean,
                desv_std = sd,
                minimo = min,
                maximo = max,
                mediana = median)
           ) #|> 
  #pivot_wider(names_from = variable, values_from = media:mediana)
aus_accommodation_long
```


```{r}
aus_accommodation_long |> 
  features(valor, feat_stl)
```

```{r}
aus_accommodation_long |> 
  features(valor, features = guerrero)
```

$$
y_t = y_{t-1} + \varepsilon_t\\
\varepsilon_t \~ N(\mu = 0, \sigma^2) \\
E[y_t] = E[y_{t-1} + \varepsilon_t] \\
E[y_t] = E[y_{t-1}] + E[\varepsilon_t]\\
E[y_t] = y_{t-1} + 0\\
E[y_t] = y_{t-1}\\
\hat{y}_t = y_{t-1}\\
\hat{y}_{T+1} = y_{T}
$$